import '@/styles/globals.css';
import { Suspense } from 'react';
import Loading from './loading';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen h-screen min-w-screen w-screen bg-zinc-800">
        <Suspense fallback={<Loading />}>{children}</Suspense>
      </body>
    </html>
  );
}
