POST http://localhost:3001/login
Content-Type: application/json

{
  "email":"test",
  "password": "nuts"
}


###
GET http://localhost:3001/test
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.ZWx4bg.HH08Mx-1nAF3ujgjlve-ykPdm3XhK0PhHYUKY2Otywc

###
GET http://localhost:3001/logout

###
GET http://localhost:3001/test