POST http://localhost:3001/login
Content-Type: application/json

{
  "email":"test",
  "password": "nuts"
}


###
GET http://localhost:3001/test


###
GET http://localhost:3001/logout

###
GET http://localhost:3001/test